CFLAGS=-fPIC

SRCS=$(wildcard *.c)

OBJS=$(SRCS:.c=.o)

%.o : %.c
	gcc -c $(CFLAGS) $< -o $@

all : $(OBJS)
	gcc -shared $(OBJS) -o liblolan.so

clean:
	rm -f *.o
	rm -f *.so

install:
	cp liblolan.so /usr/local/lib/liblolan.so
	cp lolan.h /usr/local/include/lolan.h
